-- =====================================================================
--  Tea Production — схема public для собственного сервера (timeweb.cloud)
--  Источник: Supabase project heznxwdrwyjipyracyqy (PostgreSQL 17.6)
--  Снято: 2026-07-03 через прямую интроспекцию БД.
--
--  Назначение: чистая, ванильная схема PostgreSQL 17 БЕЗ Supabase-специфики
--  (без RLS, без ролей anon/authenticated, без зависимостей от схемы auth).
--  Это ШАГ 1 миграции: переносим бизнес-данные. Слой авторизации (auth.users)
--  остаётся пока в Supabase и будет перенесён на Django на следующем шаге.
--
--  Порядок применения на новом сервере:
--    createdb -U postgres tea_production
--    psql -U postgres -d tea_production -f 01_schema_public.sql
--  Затем налить данные (см. runbook, scripts/sync_supabase_to_timeweb.sh).
-- =====================================================================

BEGIN;

-- gen_random_uuid() встроен в PostgreSQL 13+. pgcrypto добавляем на случай
-- совместимости со старыми клиентами / дополнительной криптографии.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------
-- Справочники верхнего уровня
-- ---------------------------------------------------------------------

CREATE TABLE material_categories (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name        text NOT NULL,
    description text,
    created_at  timestamptz DEFAULT now()
);

CREATE TABLE product_types (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text NOT NULL,
    sort_order integer NOT NULL DEFAULT 100,
    code       text UNIQUE,
    parent_id  integer REFERENCES product_types(id)
);

CREATE TABLE clients (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name       text NOT NULL,
    notes      text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE assortments (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    code        text NOT NULL UNIQUE,
    name        text NOT NULL,
    description text,
    created_at  timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- Сырьё и цены
-- ---------------------------------------------------------------------

CREATE TABLE raw_materials (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name        text NOT NULL,
    category_id uuid REFERENCES material_categories(id),
    unit        text NOT NULL DEFAULT 'кг',
    description text,
    supplier    text,
    is_active   boolean DEFAULT true,
    created_at  timestamptz DEFAULT now(),
    updated_at  timestamptz DEFAULT now(),
    article     text UNIQUE
);

CREATE TABLE material_prices (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    material_id    uuid NOT NULL REFERENCES raw_materials(id),
    price_per_unit numeric NOT NULL,
    valid_from     date NOT NULL DEFAULT CURRENT_DATE,
    valid_to       date,
    supplier       text,
    notes          text,
    created_at     timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------
-- Рецепты (купажи) и их состав
-- ---------------------------------------------------------------------

CREATE TABLE recipes (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name            text NOT NULL,
    description     text,
    output_quantity numeric NOT NULL DEFAULT 1,
    output_unit     text NOT NULL DEFAULT 'кг',
    notes           text,
    is_active       boolean DEFAULT true,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    article         text UNIQUE,
    photo_url       text
);

CREATE TABLE recipe_ingredients (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    recipe_id     uuid NOT NULL REFERENCES recipes(id),
    material_id   uuid REFERENCES raw_materials(id),
    quantity      numeric NOT NULL,
    unit          text NOT NULL DEFAULT 'кг',
    notes         text,
    created_at    timestamptz DEFAULT now(),
    sub_recipe_id uuid REFERENCES recipes(id)
);

-- ---------------------------------------------------------------------
-- SKU (товары), их состав и описания
-- ---------------------------------------------------------------------

CREATE TABLE products (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name         text NOT NULL,
    recipe_id    uuid REFERENCES recipes(id),
    package_size numeric,
    package_unit text DEFAULT 'г',
    description  text,
    is_active    boolean DEFAULT true,
    created_at   timestamptz DEFAULT now(),
    updated_at   timestamptz DEFAULT now(),
    article      text UNIQUE,
    type_id      integer REFERENCES product_types(id),
    photo_url    text
);

CREATE TABLE sku_recipe_components (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id  uuid NOT NULL REFERENCES products(id),
    recipe_id   uuid REFERENCES recipes(id),
    material_id uuid REFERENCES raw_materials(id),
    quantity    numeric NOT NULL,
    unit        text NOT NULL DEFAULT 'г',
    notes       text,
    created_at  timestamptz DEFAULT now()
);

CREATE TABLE product_descriptions (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id   uuid NOT NULL UNIQUE REFERENCES products(id),
    description  text,
    generated_at timestamptz,
    updated_at   timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------
-- Прайслисты (внутренние)
-- ---------------------------------------------------------------------

CREATE TABLE price_lists (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name           text NOT NULL,
    description    text,
    markup_percent numeric DEFAULT 0,
    is_active      boolean DEFAULT true,
    created_at     timestamptz DEFAULT now()
);

CREATE TABLE price_list_items (
    id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    price_list_id          uuid NOT NULL REFERENCES price_lists(id),
    product_id             uuid NOT NULL REFERENCES products(id),
    price                  numeric,
    override_markup_percent numeric,
    created_at             timestamptz DEFAULT now(),
    updated_at             timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------
-- Ассортименты (связи many-to-many)
-- ---------------------------------------------------------------------

CREATE TABLE assortment_products (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    assortment_id uuid NOT NULL REFERENCES assortments(id),
    product_id    uuid NOT NULL REFERENCES products(id),
    added_at      timestamptz NOT NULL DEFAULT now(),
    notes         text,
    client_id     uuid REFERENCES clients(id),
    UNIQUE (assortment_id, product_id)
);

CREATE TABLE assortment_recipes (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    assortment_id uuid NOT NULL REFERENCES assortments(id),
    recipe_id     uuid NOT NULL REFERENCES recipes(id),
    added_at      timestamptz NOT NULL DEFAULT now(),
    notes         text,
    UNIQUE (assortment_id, recipe_id)
);

CREATE TABLE assortment_price_lists (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    assortment_id uuid NOT NULL REFERENCES assortments(id),
    price_list_id uuid NOT NULL REFERENCES price_lists(id),
    added_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (assortment_id, price_list_id)
);

CREATE TABLE assortment_materials (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    assortment_id uuid NOT NULL REFERENCES assortments(id),
    material_id   uuid NOT NULL REFERENCES raw_materials(id),
    added_at      timestamptz NOT NULL DEFAULT now(),
    notes         text,
    UNIQUE (assortment_id, material_id)
);

-- ---------------------------------------------------------------------
-- Конструктор (проекты)
-- ---------------------------------------------------------------------

CREATE TABLE projects (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    type           text NOT NULL CHECK (type = ANY (ARRAY['recipe','sku'])),
    name           text NOT NULL,
    notes          text,
    created_at     timestamptz NOT NULL DEFAULT now(),
    linked_id      uuid,
    linked_article text,
    linked_name    text
);

CREATE TABLE project_items (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id uuid NOT NULL REFERENCES projects(id),
    material_id uuid REFERENCES raw_materials(id),
    quantity   numeric NOT NULL DEFAULT 0,
    unit       text NOT NULL DEFAULT 'г',
    created_at timestamptz NOT NULL DEFAULT now(),
    recipe_id  uuid REFERENCES recipes(id)
);

-- ---------------------------------------------------------------------
-- Пользователи и аудит
-- ВНИМАНИЕ: в Supabase managers.user_id / created_by и
-- pricelist_downloads.user_id ссылались на auth.users (схема Supabase Auth).
-- На этапе 1 схемы auth ещё нет — внешние ключи на auth.users НЕ создаём.
-- На шаге переноса авторизации на Django они станут FK на таблицу
-- пользователей Django (например, auth_user / accounts_user).
-- ---------------------------------------------------------------------

CREATE TABLE managers (
    user_id    uuid PRIMARY KEY,               -- будущий FK → пользователь Django
    full_name  text NOT NULL,
    phone      text,
    role       text NOT NULL DEFAULT 'manager' CHECK (role = ANY (ARRAY['admin','manager'])),
    is_active  boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid
);
COMMENT ON TABLE managers IS 'Профили пользователей системы (админы + менеджеры).';

CREATE TABLE pricelist_downloads (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       uuid NOT NULL,               -- будущий FK → пользователь Django
    downloaded_at timestamptz NOT NULL DEFAULT now(),
    tier          text NOT NULL CHECK (tier = ANY (ARRAY['base','opt','opt_plus','partner','key_partner','all'])),
    client_name   text,
    sku_count     integer,
    notes         text
);
COMMENT ON TABLE pricelist_downloads IS 'Аудит скачиваний клиентских прайс-листов.';

-- ---------------------------------------------------------------------
-- Индексы (вторичные; PK и UNIQUE создаются выше автоматически)
-- ---------------------------------------------------------------------

CREATE INDEX assortment_materials_assortment_id_idx ON assortment_materials (assortment_id);
CREATE INDEX assortment_materials_material_id_idx    ON assortment_materials (material_id);
CREATE INDEX assortment_price_lists_assortment_id_idx ON assortment_price_lists (assortment_id);
CREATE INDEX assortment_price_lists_price_list_id_idx ON assortment_price_lists (price_list_id);
CREATE INDEX assortment_products_assortment_id_idx  ON assortment_products (assortment_id);
CREATE INDEX assortment_products_product_id_idx     ON assortment_products (product_id);
CREATE INDEX idx_assortment_products_client_id      ON assortment_products (client_id);
CREATE INDEX assortment_recipes_assortment_id_idx   ON assortment_recipes (assortment_id);
CREATE INDEX assortment_recipes_recipe_id_idx       ON assortment_recipes (recipe_id);
CREATE INDEX idx_material_prices_material_id         ON material_prices (material_id);
CREATE INDEX idx_material_prices_valid              ON material_prices (material_id, valid_from, valid_to);
CREATE INDEX idx_price_list_items_list             ON price_list_items (price_list_id);
CREATE INDEX idx_price_list_items_product          ON price_list_items (product_id);
CREATE INDEX pricelist_downloads_user_idx          ON pricelist_downloads (user_id, downloaded_at DESC);
CREATE INDEX idx_product_descriptions_product_id    ON product_descriptions (product_id);
CREATE INDEX project_items_project_id_idx          ON project_items (project_id);
CREATE INDEX project_items_recipe_id_idx           ON project_items (recipe_id);
CREATE INDEX idx_recipe_ingredients_material        ON recipe_ingredients (material_id);
CREATE INDEX idx_recipe_ingredients_recipe          ON recipe_ingredients (recipe_id);
CREATE INDEX idx_sku_components_material            ON sku_recipe_components (material_id);
CREATE INDEX idx_sku_components_product             ON sku_recipe_components (product_id);
CREATE INDEX idx_sku_components_recipe             ON sku_recipe_components (recipe_id);

-- ---------------------------------------------------------------------
-- Расчётные VIEW (себестоимость и ценообразование)
-- Порядок важен: recipe_cost ← sku_cost ← product_pricing/manager_pricelist_v1
-- ---------------------------------------------------------------------

CREATE VIEW raw_materials_with_price AS
 SELECT rm.id, rm.article, rm.name, rm.unit, rm.category_id,
        mp.price_per_unit AS current_price,
        mp.valid_from AS price_date
   FROM raw_materials rm
   LEFT JOIN LATERAL (
        SELECT material_prices.price_per_unit, material_prices.valid_from
          FROM material_prices
         WHERE material_prices.material_id = rm.id
         ORDER BY material_prices.valid_from DESC
         LIMIT 1) mp ON true;

CREATE VIEW recipe_cost AS
 WITH RECURSIVE recipe_tree AS (
         SELECT ri.recipe_id, ri.material_id, ri.sub_recipe_id,
                ri.quantity::numeric AS qty_multiplier
           FROM recipe_ingredients ri
        UNION ALL
         SELECT rt_1.recipe_id, ri2.material_id, ri2.sub_recipe_id,
                rt_1.qty_multiplier * ri2.quantity::numeric AS qty_multiplier
           FROM recipe_tree rt_1
           JOIN recipe_ingredients ri2 ON ri2.recipe_id = rt_1.sub_recipe_id
          WHERE rt_1.sub_recipe_id IS NOT NULL
        )
 SELECT r.id AS recipe_id, r.article AS recipe_article, r.name AS recipe_name,
        r.output_quantity, r.output_unit,
        sum(rt.qty_multiplier * COALESCE((
              SELECT mp.price_per_unit FROM material_prices mp
               WHERE mp.material_id = rt.material_id
                 AND mp.valid_from <= CURRENT_DATE
                 AND (mp.valid_to IS NULL OR mp.valid_to >= CURRENT_DATE)
               ORDER BY mp.valid_from DESC LIMIT 1), 0::numeric)) AS total_cost,
        sum(rt.qty_multiplier * COALESCE((
              SELECT mp.price_per_unit FROM material_prices mp
               WHERE mp.material_id = rt.material_id
                 AND mp.valid_from <= CURRENT_DATE
                 AND (mp.valid_to IS NULL OR mp.valid_to >= CURRENT_DATE)
               ORDER BY mp.valid_from DESC LIMIT 1), 0::numeric))
          / NULLIF(r.output_quantity, 0::numeric) AS cost_per_kg
   FROM recipes r
   JOIN recipe_tree rt ON rt.recipe_id = r.id
  WHERE rt.material_id IS NOT NULL
  GROUP BY r.id, r.article, r.name, r.output_quantity, r.output_unit;

CREATE VIEW sku_cost AS
 SELECT p.id AS product_id, p.article AS sku_article, p.name AS product_name,
        p.package_size, p.package_unit,
        COALESCE(sum(CASE WHEN src.recipe_id IS NOT NULL
             THEN src.quantity * ((SELECT rc.cost_per_kg FROM recipe_cost rc WHERE rc.recipe_id = src.recipe_id))
             ELSE NULL::numeric END), 0::numeric) AS blend_cost,
        COALESCE(sum(CASE WHEN src.material_id IS NOT NULL
             THEN src.quantity * COALESCE((SELECT mp.price_per_unit FROM material_prices mp
                    WHERE mp.material_id = src.material_id
                      AND mp.valid_from <= CURRENT_DATE
                      AND (mp.valid_to IS NULL OR mp.valid_to >= CURRENT_DATE)
                    ORDER BY mp.valid_from DESC LIMIT 1), 0::numeric)
             ELSE NULL::numeric END), 0::numeric) AS packaging_cost,
        COALESCE(sum(CASE WHEN src.recipe_id IS NOT NULL
             THEN src.quantity * ((SELECT rc.cost_per_kg FROM recipe_cost rc WHERE rc.recipe_id = src.recipe_id))
             ELSE NULL::numeric END), 0::numeric)
        + COALESCE(sum(CASE WHEN src.material_id IS NOT NULL
             THEN src.quantity * COALESCE((SELECT mp.price_per_unit FROM material_prices mp
                    WHERE mp.material_id = src.material_id
                      AND mp.valid_from <= CURRENT_DATE
                      AND (mp.valid_to IS NULL OR mp.valid_to >= CURRENT_DATE)
                    ORDER BY mp.valid_from DESC LIMIT 1), 0::numeric)
             ELSE NULL::numeric END), 0::numeric) AS total_sku_cost
   FROM products p
   JOIN sku_recipe_components src ON src.product_id = p.id
  GROUP BY p.id, p.article, p.name, p.package_size, p.package_unit;

CREATE VIEW product_pricing AS
 SELECT p.id AS product_id, p.article AS sku_article, p.name AS product_name,
        p.package_size, p.package_unit, sc.total_sku_cost,
        pl.id AS price_list_id, pl.name AS price_list_name,
        COALESCE(pli.override_markup_percent, pl.markup_percent) AS markup_percent,
        COALESCE(pli.price, round(sc.total_sku_cost * (1::numeric + COALESCE(pli.override_markup_percent, pl.markup_percent) / 100::numeric), 2)) AS final_price
   FROM products p
   JOIN sku_cost sc ON sc.product_id = p.id
   CROSS JOIN price_lists pl
   LEFT JOIN price_list_items pli ON pli.product_id = p.id AND pli.price_list_id = pl.id;

-- Изолированный прайс для менеджеров: 5 уровней цен без НДС, без себестоимости.
CREATE VIEW manager_pricelist_v1 AS
 SELECT p.id AS product_id, p.article AS sku_article, p.name AS sku_name,
        p.photo_url, p.package_size, p.package_unit, pt.name AS category_name,
        round(sc.total_sku_cost * 2.70)::integer AS price_base,
        round(sc.total_sku_cost * 2.50)::integer AS price_opt,
        round(sc.total_sku_cost * 2.30)::integer AS price_opt_plus,
        round(sc.total_sku_cost * 2.10)::integer AS price_partner,
        round(sc.total_sku_cost * 1.95)::integer AS price_key_partner
   FROM products p
   LEFT JOIN product_types pt ON pt.id = p.type_id
   LEFT JOIN sku_cost sc ON sc.product_id = p.id
  WHERE p.is_active = true AND sc.total_sku_cost IS NOT NULL;

-- ---------------------------------------------------------------------
-- Триггеры автоматического наполнения ассортиментов
-- (чистая бизнес-логика, переносится как есть)
-- ---------------------------------------------------------------------

CREATE OR REPLACE FUNCTION trg_material_to_all_assortments()
 RETURNS trigger LANGUAGE plpgsql AS $function$
BEGIN
  INSERT INTO assortment_materials (assortment_id, material_id)
  SELECT a.id, NEW.id FROM assortments a
  WHERE NOT EXISTS (
    SELECT 1 FROM assortment_materials am
    WHERE am.assortment_id = a.id AND am.material_id = NEW.id);
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION trg_assortment_gets_shared()
 RETURNS trigger LANGUAGE plpgsql AS $function$
BEGIN
  INSERT INTO assortment_materials (assortment_id, material_id)
  SELECT NEW.id, m.id FROM raw_materials m
  WHERE NOT EXISTS (
    SELECT 1 FROM assortment_materials am
    WHERE am.assortment_id = NEW.id AND am.material_id = m.id);
  RETURN NEW;
END;
$function$;

CREATE TRIGGER material_to_all_assortments
  AFTER INSERT ON raw_materials
  FOR EACH ROW EXECUTE FUNCTION trg_material_to_all_assortments();

CREATE TRIGGER assortment_gets_shared
  AFTER INSERT ON assortments
  FOR EACH ROW EXECUTE FUNCTION trg_assortment_gets_shared();

COMMIT;

-- =====================================================================
--  НЕ перенесено на этапе 1 (зависит от Supabase Auth, вернём на шаге Django):
--    - VIEW auth_users_managed  (читает auth.users + is_admin())
--    - FUNCTION is_admin(), is_active_user()  (используют auth.uid())
--    - RLS-политики на managers, pricelist_downloads
--  Эту логику доступа на новом сервере обеспечит Django (permissions).
-- =====================================================================
